### ISSUE TITLE
Sometimes Report is not aggregated(created) for the test suite

### ISSUE THREAD

**Issue by andriuspit** [webdriverio-community/wdio-html-reporter#86]
Stumbled to issue that sometimes for the same test suite report is not aggregated and in logs error is displayed: "[ERROR] default - Invalid Metrics computed: undefined -- undefined"

**Comment by rpii** [comment]
Ive had another report of that.  It seems that the new json stream library
has some issue somewhere. I will have to look into it

Rich

**Comment by rpii** [comment]
this is the new code:
                let jsonFile = reportData.reportFile.replace('.html',
'.json');
                try {
                    reportOptions.LOG.info("Json write starting: " +
jsonFile );
                    (async () => {
                        await json.stringify({
                            body: reportData
                        })
                            .then(function(stringified) {
                                fs.outputFileSync(jsonFile, stringified);
                                reportOptions.LOG.info("Json write
completed: " + jsonFile );
                            })
                            .catch((error) => {
                                reportOptions.LOG.error("Json write failed:
" + error );
                            });
                    })();


can you see if the log messages are showing anything?  Have to turn that
logging on

Rich

**Comment by andriuspit** [comment]
Should I put this provided code snippet somewhere?

But looking at debug level logs of report aggregator there some logs that contain javascript code, that maybe could not be stringified (?). Node: Tests use "wdio-intercept-service"

Example:

`[2022-04-25T09:07:50.360] [DEBUG] debug - {"type":"test","start":"2022-04-25T06:07:50.352Z","_duration":7,"uid":"test-10-4","cid":"0-0","title":"should display \"Task End\" filer values in descending order","fullTitle":"Tasks.When I go to Tasks page and open date columns filters.should display \"Task End\" filer values in descending order","output":[{"method":"POST","endpoint":"/session/:sessionId/execute/async","body":{"script":"return (function setup(done) {\n    var NAMESPACE = '__webdriverajax';\n    var PKG_PREFIX = '[wdio-intercept-service]: ';\n\n    window[NAMESPACE] = { requests: [] };\n\n    // Some browsers don't support FormData.entries(), so we polyfill that (sigh)\n    if (typeof FormData.prototype.entries == 'undefined') {\n      polyfillFormDataEntries();\n    }\n\n    if (supportsSessionStorage()) {\n      window.sessionStorage.removeItem(NAMESPACE);\n    }\n\n    if (typeof window.fetch == 'function') {\n      replaceFetch();\n      if (\n        typeof window.Promise === 'undefined' ||\n        typeof window.Promise.all !== 'function'\n      ) {\n        console.error(PKG_PREFIX + 'Fetch API preconditions not met!');\n      }\n    }\n\n    replaceXHR();\n\n    done(window[NAMESPACE]);\n\n    function replaceFetch() {\n      var _fetch = window.fetch;\n      window.fetch = function () {\n        // Default values if not overwritten\n        var request = {\n          method: 'GET',\n          requestHeaders: {},\n          requestBody: undefined,\n          url: '',\n        };\n        var input = arguments[0];\n        var init = arguments[1];\n        if (typeof input == 'string') {\n          request.url = input;\n        } else if (input instanceof URL) {\n          request.url = input.href;\n        } else {\n          if (input instanceof Request) {\n            // Request object\n            var clonedRequest = input.clone();\n            request.requestBody = clonedRequest.text();\n            request.url = clonedRequest.url;\n            request.requestHeaders = parseHeaders(clonedRequest.headers);\n            request.method = clonedRequest.method;\n          } else {\n            console.error(PKG_PREFIX + 'Unhandled input type to fetch API!');\n            request.requestBody = input.body;\n          }\n        }\n        if (init) {\n          if (typeof init.body !== 'undefined') request.requestBody = parsePayload(init.body);\n          if (typeof init.method !== 'undefined') request.method = init.method;\n          request.requestHeaders = parseHeaders(init.headers);\n        }\n        addPendingRequest(request);\n\n        return _fetch.apply(window, arguments).then(function (response) {\n          // TODO: We could clone it multiple times and check for all type variations of body\n          var clonedResponse = response.clone();\n          var responsePromise = clonedResponse.text();\n\n          // After decoding the request's body (which may have come from Request#text())\n          // and the response body, we can store the completed request.\n          Promise.all([request.requestBody, responsePromise]).then(function (\n            results\n          ) {\n            completeFetchRequest(request, {\n              requestBody: results[0],\n              body: results[1],\n              statusCode: clonedResponse.status,\n              headers: parseHeaders(clonedResponse.headers),\n            });\n          });\n\n          // Forward the original response to the application on the current tick.\n          return response;\n        });\n      };\n    }\n\n    function replaceXHR() {\n      var originalOpen = XMLHttpRequest.prototype.open;\n      var originalSend = XMLHttpRequest.prototype.send;\n      var originalSetRequestHeader = XMLHttpRequest.prototype.setRequestHeader;\n      var originalAbort = XMLHttpRequest.prototype.abort;\n      var handleDoneRequest = function (xhr) {\n        if (xhr.readyState == XMLHttpRequest.prototype.DONE) {\n          var req = xhr.lastReq;\n          req.statusCode = xhr.status;\n          req.headers = xhr.getAllResponseHeaders();\n          // The body may need to be further processed, or may be ready synchronously.\n          var parsed = parseBody(xhr, req);\n          if (!parsed.deferred) {\n            completeXHRRequest(req, parsed.body);\n          }\n        }\n      };\n      XMLHttpRequest.prototype.open = function () {\n        this.lastMethod = arguments[0];\n        this.lastURL = arguments[1];\n        originalOpen.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.send = function () {\n        this.lastReq = {\n          method: this.lastMethod.toUpperCase(),\n          requestHeaders: this.lastRequestHeader || {},\n          requestBody: parsePayload(arguments[0]),\n          url: this.lastURL.toString(),\n        };\n        addPendingRequest(this.lastReq);\n        originalSend.apply(this, arguments);\n\n        var _this = this;\n        this.addEventListener('load', function () {\n          handleDoneRequest(_this);\n        });\n      };\n      XMLHttpRequest.prototype.setRequestHeader = function () {\n        if (!this.lastRequestHeader) {\n          this.lastRequestHeader = {};\n        }\n        this.lastRequestHeader[arguments[0]] = arguments[1];\n        originalSetRequestHeader.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.abort = function () {\n        handleDoneRequest(this);\n        originalAbort.apply(this, arguments);\n      };\n    }\n\n    function parseBody(xhr, request) {\n      if (xhr.responseType === 'arraybuffer') {\n        return {\n          body: new TextDecoder().decode(xhr.response),\n        };\n      } else if (xhr.responseType === 'blob') {\n        // Read the response like a file.\n        var fr = new FileReader();\n        fr.addEventListener('load', function () {\n          completeXHRRequest(request, new TextDecoder().decode(this.result));\n        });\n        fr.readAsArrayBuffer(xhr.response);\n        return { deferred: true };\n      }\n      // IE9 comp: need xhr.responseText\n      return {\n        body: xhr.response || xhr.responseText,\n      };\n    }\n\n    function parseHeaders(headers) {\n      if (headers instanceof Headers) {\n        var result = {};\n\n        var headersEntries = headers.entries();\n        var header = headersEntries.next();\n        while (!header.done) {\n          result[header.value[0]] = header.value[1];\n          header = headersEntries.next();\n        }\n        return result;\n      }\n      return headers || {};\n    }\n\n    /**\n     * Stringify the given XHR payload so it can be parsed as JSON\n     * @param {*} payload XHR request body that is sent to the remote server.\n     * @returns {string} JSON-parsable representation of the request body\n     */\n    function parsePayload(payload) {\n      if (typeof payload == 'string') {\n        return payload;\n      }\n      if (payload instanceof FormData) {\n        var parsed = {};\n        var entries = payload.entries();\n        var item;\n        while (((item = entries.next()), !item.done)) {\n          parsed[item.value[0]] = item.value.slice(1);\n        }\n        return JSON.stringify(parsed);\n      }\n      if (payload instanceof ArrayBuffer) {\n        return String.fromCharCode.apply(null, payload);\n      }\n      if (payload instanceof URLSearchParams) {\n        return payload.toString();\n      }\n\n      // Just try to convert it to a string, whatever it might be\n      try {\n        return JSON.stringify(payload);\n      } catch (e) {\n        console.error(PKG_PREFIX + 'Failed to stringify payload as JSON!', e);\n      }\n      return '';\n    }\n\n    function addPendingRequest(startedRequest) {\n      startedRequest.__processed = Date.now();\n      window[NAMESPACE].requests.push(startedRequest);\n      pushToSessionStorage(startedRequest);\n    }\n\n    function completeFetchRequest(startedRequest, completedRequest) {\n      // Merge the completed data with the started request.\n      startedRequest.requestBody = completedRequest.requestBody;\n      startedRequest.body = completedRequest.body;\n      startedRequest.headers = completedRequest.headers;\n      startedRequest.statusCode = completedRequest.statusCode;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function completeXHRRequest(startedRequest, responseBody) {\n      // Merge the completed data with the started request.\n      startedRequest.body = responseBody;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function getParsedSessionStorage() {\n      var rawData = window.sessionStorage.getItem(NAMESPACE);\n      if (!rawData) {\n        return [];\n      }\n      try {\n        return JSON.parse(rawData);\n      } catch (e) {\n        throw new Error(\n          PKG_PREFIX + 'Could not parse sessionStorage data: ' + e.message\n        );\n      }\n    }\n\n    function supportsSessionStorage() {\n      return (\n        typeof window.sessionStorage === 'object' &&\n        window.sessionStorage !== null &&\n        typeof window.sessionStorage.setItem === 'function' &&\n        typeof window.sessionStorage.removeItem === 'function'\n      );\n    }\n\n    function pushToSessionStorage(req) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      parsed.push(req);\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function replaceInSessionStorage(completedRequest) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      // Unlike requests held in the namespace, no session-stored requests can share object equality\n      // with the completed request, due to the string serialization. Instead, we must look for an\n      // item with the same \"__processed\" time. In case multiple requests are added simultaneously,\n      // the url and method are used to further disambiguate the serialized requests.\n      for (\n        var storedRqNumber = 0;\n        storedRqNumber < parsed.length;\n        ++storedRqNumber\n      ) {\n        var r = parsed[storedRqNumber];\n        if (\n          r.__processed === completedRequest.__processed &&\n          r.url === completedRequest.url &&\n          r.method === completedRequest.method\n        ) {\n          parsed[storedRqNumber] = completedRequest;\n          break;\n        }\n      }\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function polyfillFormDataEntries() {\n      var originalAppend = FormData.prototype.append;\n      FormData.prototype.append = function () {\n        this.__entries = this.__entries || [];\n        this.__entries.push(Array.prototype.slice.call(arguments));\n        originalAppend.apply(this, arguments);\n      };\n      FormData.prototype.entries = function () {\n        return this.__entries;\n      };\n    }\n  }).apply(null, arguments)","args":[]},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"command"},{"method":"POST","endpoint":"/session/:sessionId/se/log","body":{"type":"browser"},"result":{"value":[]},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"result"},{"method":"POST","endpoint":"/session/:sessionId/execute/async","body":{"script":"return (function setup(done) {\n    var NAMESPACE = '__webdriverajax';\n    var PKG_PREFIX = '[wdio-intercept-service]: ';\n\n    window[NAMESPACE] = { requests: [] };\n\n    // Some browsers don't support FormData.entries(), so we polyfill that (sigh)\n    if (typeof FormData.prototype.entries == 'undefined') {\n      polyfillFormDataEntries();\n    }\n\n    if (supportsSessionStorage()) {\n      window.sessionStorage.removeItem(NAMESPACE);\n    }\n\n    if (typeof window.fetch == 'function') {\n      replaceFetch();\n      if (\n        typeof window.Promise === 'undefined' ||\n        typeof window.Promise.all !== 'function'\n      ) {\n        console.error(PKG_PREFIX + 'Fetch API preconditions not met!');\n      }\n    }\n\n    replaceXHR();\n\n    done(window[NAMESPACE]);\n\n    function replaceFetch() {\n      var _fetch = window.fetch;\n      window.fetch = function () {\n        // Default values if not overwritten\n        var request = {\n          method: 'GET',\n          requestHeaders: {},\n          requestBody: undefined,\n          url: '',\n        };\n        var input = arguments[0];\n        var init = arguments[1];\n        if (typeof input == 'string') {\n          request.url = input;\n        } else if (input instanceof URL) {\n          request.url = input.href;\n        } else {\n          if (input instanceof Request) {\n            // Request object\n            var clonedRequest = input.clone();\n            request.requestBody = clonedRequest.text();\n            request.url = clonedRequest.url;\n            request.requestHeaders = parseHeaders(clonedRequest.headers);\n            request.method = clonedRequest.method;\n          } else {\n            console.error(PKG_PREFIX + 'Unhandled input type to fetch API!');\n            request.requestBody = input.body;\n          }\n        }\n        if (init) {\n          if (typeof init.body !== 'undefined') request.requestBody = parsePayload(init.body);\n          if (typeof init.method !== 'undefined') request.method = init.method;\n          request.requestHeaders = parseHeaders(init.headers);\n        }\n        addPendingRequest(request);\n\n        return _fetch.apply(window, arguments).then(function (response) {\n          // TODO: We could clone it multiple times and check for all type variations of body\n          var clonedResponse = response.clone();\n          var responsePromise = clonedResponse.text();\n\n          // After decoding the request's body (which may have come from Request#text())\n          // and the response body, we can store the completed request.\n          Promise.all([request.requestBody, responsePromise]).then(function (\n            results\n          ) {\n            completeFetchRequest(request, {\n              requestBody: results[0],\n              body: results[1],\n              statusCode: clonedResponse.status,\n              headers: parseHeaders(clonedResponse.headers),\n            });\n          });\n\n          // Forward the original response to the application on the current tick.\n          return response;\n        });\n      };\n    }\n\n    function replaceXHR() {\n      var originalOpen = XMLHttpRequest.prototype.open;\n      var originalSend = XMLHttpRequest.prototype.send;\n      var originalSetRequestHeader = XMLHttpRequest.prototype.setRequestHeader;\n      var originalAbort = XMLHttpRequest.prototype.abort;\n      var handleDoneRequest = function (xhr) {\n        if (xhr.readyState == XMLHttpRequest.prototype.DONE) {\n          var req = xhr.lastReq;\n          req.statusCode = xhr.status;\n          req.headers = xhr.getAllResponseHeaders();\n          // The body may need to be further processed, or may be ready synchronously.\n          var parsed = parseBody(xhr, req);\n          if (!parsed.deferred) {\n            completeXHRRequest(req, parsed.body);\n          }\n        }\n      };\n      XMLHttpRequest.prototype.open = function () {\n        this.lastMethod = arguments[0];\n        this.lastURL = arguments[1];\n        originalOpen.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.send = function () {\n        this.lastReq = {\n          method: this.lastMethod.toUpperCase(),\n          requestHeaders: this.lastRequestHeader || {},\n          requestBody: parsePayload(arguments[0]),\n          url: this.lastURL.toString(),\n        };\n        addPendingRequest(this.lastReq);\n        originalSend.apply(this, arguments);\n\n        var _this = this;\n        this.addEventListener('load', function () {\n          handleDoneRequest(_this);\n        });\n      };\n      XMLHttpRequest.prototype.setRequestHeader = function () {\n        if (!this.lastRequestHeader) {\n          this.lastRequestHeader = {};\n        }\n        this.lastRequestHeader[arguments[0]] = arguments[1];\n        originalSetRequestHeader.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.abort = function () {\n        handleDoneRequest(this);\n        originalAbort.apply(this, arguments);\n      };\n    }\n\n    function parseBody(xhr, request) {\n      if (xhr.responseType === 'arraybuffer') {\n        return {\n          body: new TextDecoder().decode(xhr.response),\n        };\n      } else if (xhr.responseType === 'blob') {\n        // Read the response like a file.\n        var fr = new FileReader();\n        fr.addEventListener('load', function () {\n          completeXHRRequest(request, new TextDecoder().decode(this.result));\n        });\n        fr.readAsArrayBuffer(xhr.response);\n        return { deferred: true };\n      }\n      // IE9 comp: need xhr.responseText\n      return {\n        body: xhr.response || xhr.responseText,\n      };\n    }\n\n    function parseHeaders(headers) {\n      if (headers instanceof Headers) {\n        var result = {};\n\n        var headersEntries = headers.entries();\n        var header = headersEntries.next();\n        while (!header.done) {\n          result[header.value[0]] = header.value[1];\n          header = headersEntries.next();\n        }\n        return result;\n      }\n      return headers || {};\n    }\n\n    /**\n     * Stringify the given XHR payload so it can be parsed as JSON\n     * @param {*} payload XHR request body that is sent to the remote server.\n     * @returns {string} JSON-parsable representation of the request body\n     */\n    function parsePayload(payload) {\n      if (typeof payload == 'string') {\n        return payload;\n      }\n      if (payload instanceof FormData) {\n        var parsed = {};\n        var entries = payload.entries();\n        var item;\n        while (((item = entries.next()), !item.done)) {\n          parsed[item.value[0]] = item.value.slice(1);\n        }\n        return JSON.stringify(parsed);\n      }\n      if (payload instanceof ArrayBuffer) {\n        return String.fromCharCode.apply(null, payload);\n      }\n      if (payload instanceof URLSearchParams) {\n        return payload.toString();\n      }\n\n      // Just try to convert it to a string, whatever it might be\n      try {\n        return JSON.stringify(payload);\n      } catch (e) {\n        console.error(PKG_PREFIX + 'Failed to stringify payload as JSON!', e);\n      }\n      return '';\n    }\n\n    function addPendingRequest(startedRequest) {\n      startedRequest.__processed = Date.now();\n      window[NAMESPACE].requests.push(startedRequest);\n      pushToSessionStorage(startedRequest);\n    }\n\n    function completeFetchRequest(startedRequest, completedRequest) {\n      // Merge the completed data with the started request.\n      startedRequest.requestBody = completedRequest.requestBody;\n      startedRequest.body = completedRequest.body;\n      startedRequest.headers = completedRequest.headers;\n      startedRequest.statusCode = completedRequest.statusCode;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function completeXHRRequest(startedRequest, responseBody) {\n      // Merge the completed data with the started request.\n      startedRequest.body = responseBody;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function getParsedSessionStorage() {\n      var rawData = window.sessionStorage.getItem(NAMESPACE);\n      if (!rawData) {\n        return [];\n      }\n      try {\n        return JSON.parse(rawData);\n      } catch (e) {\n        throw new Error(\n          PKG_PREFIX + 'Could not parse sessionStorage data: ' + e.message\n        );\n      }\n    }\n\n    function supportsSessionStorage() {\n      return (\n        typeof window.sessionStorage === 'object' &&\n        window.sessionStorage !== null &&\n        typeof window.sessionStorage.setItem === 'function' &&\n        typeof window.sessionStorage.removeItem === 'function'\n      );\n    }\n\n    function pushToSessionStorage(req) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      parsed.push(req);\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function replaceInSessionStorage(completedRequest) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      // Unlike requests held in the namespace, no session-stored requests can share object equality\n      // with the completed request, due to the string serialization. Instead, we must look for an\n      // item with the same \"__processed\" time. In case multiple requests are added simultaneously,\n      // the url and method are used to further disambiguate the serialized requests.\n      for (\n        var storedRqNumber = 0;\n        storedRqNumber < parsed.length;\n        ++storedRqNumber\n      ) {\n        var r = parsed[storedRqNumber];\n        if (\n          r.__processed === completedRequest.__processed &&\n          r.url === completedRequest.url &&\n          r.method === completedRequest.method\n        ) {\n          parsed[storedRqNumber] = completedRequest;\n          break;\n        }\n      }\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function polyfillFormDataEntries() {\n      var originalAppend = FormData.prototype.append;\n      FormData.prototype.append = function () {\n        this.__entries = this.__entries || [];\n        this.__entries.push(Array.prototype.slice.call(arguments));\n        originalAppend.apply(this, arguments);\n      };\n      FormData.prototype.entries = function () {\n        return this.__entries;\n      };\n    }\n  }).apply(null, arguments)","args":[]},"result":{"value":{"requests":[]}},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"result"},{"name":"setupInterceptor","result":{"requests":[]},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"result"}],"retries":0,"state":"passed","events":[],"errorIndex":0,"end":"2022-04-25T06:07:50.359Z"}
[2022-04-25T09:07:50.360] [INFO] debug - onTestEnd: 0-0:test-10-4
[2022-04-25T09:07:50.360] [DEBUG] debug - {"type":"test","start":"2022-04-25T06:07:50.352Z","_duration":7,"uid":"test-10-4","cid":"0-0","title":"should display \"Task End\" filer values in descending order","fullTitle":"Tasks.When I go to Tasks page and open date columns filters.should display \"Task End\" filer values in descending order","output":[{"method":"POST","endpoint":"/session/:sessionId/execute/async","body":{"script":"return (function setup(done) {\n    var NAMESPACE = '__webdriverajax';\n    var PKG_PREFIX = '[wdio-intercept-service]: ';\n\n    window[NAMESPACE] = { requests: [] };\n\n    // Some browsers don't support FormData.entries(), so we polyfill that (sigh)\n    if (typeof FormData.prototype.entries == 'undefined') {\n      polyfillFormDataEntries();\n    }\n\n    if (supportsSessionStorage()) {\n      window.sessionStorage.removeItem(NAMESPACE);\n    }\n\n    if (typeof window.fetch == 'function') {\n      replaceFetch();\n      if (\n        typeof window.Promise === 'undefined' ||\n        typeof window.Promise.all !== 'function'\n      ) {\n        console.error(PKG_PREFIX + 'Fetch API preconditions not met!');\n      }\n    }\n\n    replaceXHR();\n\n    done(window[NAMESPACE]);\n\n    function replaceFetch() {\n      var _fetch = window.fetch;\n      window.fetch = function () {\n        // Default values if not overwritten\n        var request = {\n          method: 'GET',\n          requestHeaders: {},\n          requestBody: undefined,\n          url: '',\n        };\n        var input = arguments[0];\n        var init = arguments[1];\n        if (typeof input == 'string') {\n          request.url = input;\n        } else if (input instanceof URL) {\n          request.url = input.href;\n        } else {\n          if (input instanceof Request) {\n            // Request object\n            var clonedRequest = input.clone();\n            request.requestBody = clonedRequest.text();\n            request.url = clonedRequest.url;\n            request.requestHeaders = parseHeaders(clonedRequest.headers);\n            request.method = clonedRequest.method;\n          } else {\n            console.error(PKG_PREFIX + 'Unhandled input type to fetch API!');\n            request.requestBody = input.body;\n          }\n        }\n        if (init) {\n          if (typeof init.body !== 'undefined') request.requestBody = parsePayload(init.body);\n          if (typeof init.method !== 'undefined') request.method = init.method;\n          request.requestHeaders = parseHeaders(init.headers);\n        }\n        addPendingRequest(request);\n\n        return _fetch.apply(window, arguments).then(function (response) {\n          // TODO: We could clone it multiple times and check for all type variations of body\n          var clonedResponse = response.clone();\n          var responsePromise = clonedResponse.text();\n\n          // After decoding the request's body (which may have come from Request#text())\n          // and the response body, we can store the completed request.\n          Promise.all([request.requestBody, responsePromise]).then(function (\n            results\n          ) {\n            completeFetchRequest(request, {\n              requestBody: results[0],\n              body: results[1],\n              statusCode: clonedResponse.status,\n              headers: parseHeaders(clonedResponse.headers),\n            });\n          });\n\n          // Forward the original response to the application on the current tick.\n          return response;\n        });\n      };\n    }\n\n    function replaceXHR() {\n      var originalOpen = XMLHttpRequest.prototype.open;\n      var originalSend = XMLHttpRequest.prototype.send;\n      var originalSetRequestHeader = XMLHttpRequest.prototype.setRequestHeader;\n      var originalAbort = XMLHttpRequest.prototype.abort;\n      var handleDoneRequest = function (xhr) {\n        if (xhr.readyState == XMLHttpRequest.prototype.DONE) {\n          var req = xhr.lastReq;\n          req.statusCode = xhr.status;\n          req.headers = xhr.getAllResponseHeaders();\n          // The body may need to be further processed, or may be ready synchronously.\n          var parsed = parseBody(xhr, req);\n          if (!parsed.deferred) {\n            completeXHRRequest(req, parsed.body);\n          }\n        }\n      };\n      XMLHttpRequest.prototype.open = function () {\n        this.lastMethod = arguments[0];\n        this.lastURL = arguments[1];\n        originalOpen.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.send = function () {\n        this.lastReq = {\n          method: this.lastMethod.toUpperCase(),\n          requestHeaders: this.lastRequestHeader || {},\n          requestBody: parsePayload(arguments[0]),\n          url: this.lastURL.toString(),\n        };\n        addPendingRequest(this.lastReq);\n        originalSend.apply(this, arguments);\n\n        var _this = this;\n        this.addEventListener('load', function () {\n          handleDoneRequest(_this);\n        });\n      };\n      XMLHttpRequest.prototype.setRequestHeader = function () {\n        if (!this.lastRequestHeader) {\n          this.lastRequestHeader = {};\n        }\n        this.lastRequestHeader[arguments[0]] = arguments[1];\n        originalSetRequestHeader.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.abort = function () {\n        handleDoneRequest(this);\n        originalAbort.apply(this, arguments);\n      };\n    }\n\n    function parseBody(xhr, request) {\n      if (xhr.responseType === 'arraybuffer') {\n        return {\n          body: new TextDecoder().decode(xhr.response),\n        };\n      } else if (xhr.responseType === 'blob') {\n        // Read the response like a file.\n        var fr = new FileReader();\n        fr.addEventListener('load', function () {\n          completeXHRRequest(request, new TextDecoder().decode(this.result));\n        });\n        fr.readAsArrayBuffer(xhr.response);\n        return { deferred: true };\n      }\n      // IE9 comp: need xhr.responseText\n      return {\n        body: xhr.response || xhr.responseText,\n      };\n    }\n\n    function parseHeaders(headers) {\n      if (headers instanceof Headers) {\n        var result = {};\n\n        var headersEntries = headers.entries();\n        var header = headersEntries.next();\n        while (!header.done) {\n          result[header.value[0]] = header.value[1];\n          header = headersEntries.next();\n        }\n        return result;\n      }\n      return headers || {};\n    }\n\n    /**\n     * Stringify the given XHR payload so it can be parsed as JSON\n     * @param {*} payload XHR request body that is sent to the remote server.\n     * @returns {string} JSON-parsable representation of the request body\n     */\n    function parsePayload(payload) {\n      if (typeof payload == 'string') {\n        return payload;\n      }\n      if (payload instanceof FormData) {\n        var parsed = {};\n        var entries = payload.entries();\n        var item;\n        while (((item = entries.next()), !item.done)) {\n          parsed[item.value[0]] = item.value.slice(1);\n        }\n        return JSON.stringify(parsed);\n      }\n      if (payload instanceof ArrayBuffer) {\n        return String.fromCharCode.apply(null, payload);\n      }\n      if (payload instanceof URLSearchParams) {\n        return payload.toString();\n      }\n\n      // Just try to convert it to a string, whatever it might be\n      try {\n        return JSON.stringify(payload);\n      } catch (e) {\n        console.error(PKG_PREFIX + 'Failed to stringify payload as JSON!', e);\n      }\n      return '';\n    }\n\n    function addPendingRequest(startedRequest) {\n      startedRequest.__processed = Date.now();\n      window[NAMESPACE].requests.push(startedRequest);\n      pushToSessionStorage(startedRequest);\n    }\n\n    function completeFetchRequest(startedRequest, completedRequest) {\n      // Merge the completed data with the started request.\n      startedRequest.requestBody = completedRequest.requestBody;\n      startedRequest.body = completedRequest.body;\n      startedRequest.headers = completedRequest.headers;\n      startedRequest.statusCode = completedRequest.statusCode;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function completeXHRRequest(startedRequest, responseBody) {\n      // Merge the completed data with the started request.\n      startedRequest.body = responseBody;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function getParsedSessionStorage() {\n      var rawData = window.sessionStorage.getItem(NAMESPACE);\n      if (!rawData) {\n        return [];\n      }\n      try {\n        return JSON.parse(rawData);\n      } catch (e) {\n        throw new Error(\n          PKG_PREFIX + 'Could not parse sessionStorage data: ' + e.message\n        );\n      }\n    }\n\n    function supportsSessionStorage() {\n      return (\n        typeof window.sessionStorage === 'object' &&\n        window.sessionStorage !== null &&\n        typeof window.sessionStorage.setItem === 'function' &&\n        typeof window.sessionStorage.removeItem === 'function'\n      );\n    }\n\n    function pushToSessionStorage(req) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      parsed.push(req);\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function replaceInSessionStorage(completedRequest) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      // Unlike requests held in the namespace, no session-stored requests can share object equality\n      // with the completed request, due to the string serialization. Instead, we must look for an\n      // item with the same \"__processed\" time. In case multiple requests are added simultaneously,\n      // the url and method are used to further disambiguate the serialized requests.\n      for (\n        var storedRqNumber = 0;\n        storedRqNumber < parsed.length;\n        ++storedRqNumber\n      ) {\n        var r = parsed[storedRqNumber];\n        if (\n          r.__processed === completedRequest.__processed &&\n          r.url === completedRequest.url &&\n          r.method === completedRequest.method\n        ) {\n          parsed[storedRqNumber] = completedRequest;\n          break;\n        }\n      }\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function polyfillFormDataEntries() {\n      var originalAppend = FormData.prototype.append;\n      FormData.prototype.append = function () {\n        this.__entries = this.__entries || [];\n        this.__entries.push(Array.prototype.slice.call(arguments));\n        originalAppend.apply(this, arguments);\n      };\n      FormData.prototype.entries = function () {\n        return this.__entries;\n      };\n    }\n  }).apply(null, arguments)","args":[]},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"command"},{"method":"POST","endpoint":"/session/:sessionId/se/log","body":{"type":"browser"},"result":{"value":[]},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"result"},{"method":"POST","endpoint":"/session/:sessionId/execute/async","body":{"script":"return (function setup(done) {\n    var NAMESPACE = '__webdriverajax';\n    var PKG_PREFIX = '[wdio-intercept-service]: ';\n\n    window[NAMESPACE] = { requests: [] };\n\n    // Some browsers don't support FormData.entries(), so we polyfill that (sigh)\n    if (typeof FormData.prototype.entries == 'undefined') {\n      polyfillFormDataEntries();\n    }\n\n    if (supportsSessionStorage()) {\n      window.sessionStorage.removeItem(NAMESPACE);\n    }\n\n    if (typeof window.fetch == 'function') {\n      replaceFetch();\n      if (\n        typeof window.Promise === 'undefined' ||\n        typeof window.Promise.all !== 'function'\n      ) {\n        console.error(PKG_PREFIX + 'Fetch API preconditions not met!');\n      }\n    }\n\n    replaceXHR();\n\n    done(window[NAMESPACE]);\n\n    function replaceFetch() {\n      var _fetch = window.fetch;\n      window.fetch = function () {\n        // Default values if not overwritten\n        var request = {\n          method: 'GET',\n          requestHeaders: {},\n          requestBody: undefined,\n          url: '',\n        };\n        var input = arguments[0];\n        var init = arguments[1];\n        if (typeof input == 'string') {\n          request.url = input;\n        } else if (input instanceof URL) {\n          request.url = input.href;\n        } else {\n          if (input instanceof Request) {\n            // Request object\n            var clonedRequest = input.clone();\n            request.requestBody = clonedRequest.text();\n            request.url = clonedRequest.url;\n            request.requestHeaders = parseHeaders(clonedRequest.headers);\n            request.method = clonedRequest.method;\n          } else {\n            console.error(PKG_PREFIX + 'Unhandled input type to fetch API!');\n            request.requestBody = input.body;\n          }\n        }\n        if (init) {\n          if (typeof init.body !== 'undefined') request.requestBody = parsePayload(init.body);\n          if (typeof init.method !== 'undefined') request.method = init.method;\n          request.requestHeaders = parseHeaders(init.headers);\n        }\n        addPendingRequest(request);\n\n        return _fetch.apply(window, arguments).then(function (response) {\n          // TODO: We could clone it multiple times and check for all type variations of body\n          var clonedResponse = response.clone();\n          var responsePromise = clonedResponse.text();\n\n          // After decoding the request's body (which may have come from Request#text())\n          // and the response body, we can store the completed request.\n          Promise.all([request.requestBody, responsePromise]).then(function (\n            results\n          ) {\n            completeFetchRequest(request, {\n              requestBody: results[0],\n              body: results[1],\n              statusCode: clonedResponse.status,\n              headers: parseHeaders(clonedResponse.headers),\n            });\n          });\n\n          // Forward the original response to the application on the current tick.\n          return response;\n        });\n      };\n    }\n\n    function replaceXHR() {\n      var originalOpen = XMLHttpRequest.prototype.open;\n      var originalSend = XMLHttpRequest.prototype.send;\n      var originalSetRequestHeader = XMLHttpRequest.prototype.setRequestHeader;\n      var originalAbort = XMLHttpRequest.prototype.abort;\n      var handleDoneRequest = function (xhr) {\n        if (xhr.readyState == XMLHttpRequest.prototype.DONE) {\n          var req = xhr.lastReq;\n          req.statusCode = xhr.status;\n          req.headers = xhr.getAllResponseHeaders();\n          // The body may need to be further processed, or may be ready synchronously.\n          var parsed = parseBody(xhr, req);\n          if (!parsed.deferred) {\n            completeXHRRequest(req, parsed.body);\n          }\n        }\n      };\n      XMLHttpRequest.prototype.open = function () {\n        this.lastMethod = arguments[0];\n        this.lastURL = arguments[1];\n        originalOpen.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.send = function () {\n        this.lastReq = {\n          method: this.lastMethod.toUpperCase(),\n          requestHeaders: this.lastRequestHeader || {},\n          requestBody: parsePayload(arguments[0]),\n          url: this.lastURL.toString(),\n        };\n        addPendingRequest(this.lastReq);\n        originalSend.apply(this, arguments);\n\n        var _this = this;\n        this.addEventListener('load', function () {\n          handleDoneRequest(_this);\n        });\n      };\n      XMLHttpRequest.prototype.setRequestHeader = function () {\n        if (!this.lastRequestHeader) {\n          this.lastRequestHeader = {};\n        }\n        this.lastRequestHeader[arguments[0]] = arguments[1];\n        originalSetRequestHeader.apply(this, arguments);\n      };\n      XMLHttpRequest.prototype.abort = function () {\n        handleDoneRequest(this);\n        originalAbort.apply(this, arguments);\n      };\n    }\n\n    function parseBody(xhr, request) {\n      if (xhr.responseType === 'arraybuffer') {\n        return {\n          body: new TextDecoder().decode(xhr.response),\n        };\n      } else if (xhr.responseType === 'blob') {\n        // Read the response like a file.\n        var fr = new FileReader();\n        fr.addEventListener('load', function () {\n          completeXHRRequest(request, new TextDecoder().decode(this.result));\n        });\n        fr.readAsArrayBuffer(xhr.response);\n        return { deferred: true };\n      }\n      // IE9 comp: need xhr.responseText\n      return {\n        body: xhr.response || xhr.responseText,\n      };\n    }\n\n    function parseHeaders(headers) {\n      if (headers instanceof Headers) {\n        var result = {};\n\n        var headersEntries = headers.entries();\n        var header = headersEntries.next();\n        while (!header.done) {\n          result[header.value[0]] = header.value[1];\n          header = headersEntries.next();\n        }\n        return result;\n      }\n      return headers || {};\n    }\n\n    /**\n     * Stringify the given XHR payload so it can be parsed as JSON\n     * @param {*} payload XHR request body that is sent to the remote server.\n     * @returns {string} JSON-parsable representation of the request body\n     */\n    function parsePayload(payload) {\n      if (typeof payload == 'string') {\n        return payload;\n      }\n      if (payload instanceof FormData) {\n        var parsed = {};\n        var entries = payload.entries();\n        var item;\n        while (((item = entries.next()), !item.done)) {\n          parsed[item.value[0]] = item.value.slice(1);\n        }\n        return JSON.stringify(parsed);\n      }\n      if (payload instanceof ArrayBuffer) {\n        return String.fromCharCode.apply(null, payload);\n      }\n      if (payload instanceof URLSearchParams) {\n        return payload.toString();\n      }\n\n      // Just try to convert it to a string, whatever it might be\n      try {\n        return JSON.stringify(payload);\n      } catch (e) {\n        console.error(PKG_PREFIX + 'Failed to stringify payload as JSON!', e);\n      }\n      return '';\n    }\n\n    function addPendingRequest(startedRequest) {\n      startedRequest.__processed = Date.now();\n      window[NAMESPACE].requests.push(startedRequest);\n      pushToSessionStorage(startedRequest);\n    }\n\n    function completeFetchRequest(startedRequest, completedRequest) {\n      // Merge the completed data with the started request.\n      startedRequest.requestBody = completedRequest.requestBody;\n      startedRequest.body = completedRequest.body;\n      startedRequest.headers = completedRequest.headers;\n      startedRequest.statusCode = completedRequest.statusCode;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function completeXHRRequest(startedRequest, responseBody) {\n      // Merge the completed data with the started request.\n      startedRequest.body = responseBody;\n      startedRequest.__fulfilled = Date.now();\n      replaceInSessionStorage(startedRequest);\n    }\n\n    function getParsedSessionStorage() {\n      var rawData = window.sessionStorage.getItem(NAMESPACE);\n      if (!rawData) {\n        return [];\n      }\n      try {\n        return JSON.parse(rawData);\n      } catch (e) {\n        throw new Error(\n          PKG_PREFIX + 'Could not parse sessionStorage data: ' + e.message\n        );\n      }\n    }\n\n    function supportsSessionStorage() {\n      return (\n        typeof window.sessionStorage === 'object' &&\n        window.sessionStorage !== null &&\n        typeof window.sessionStorage.setItem === 'function' &&\n        typeof window.sessionStorage.removeItem === 'function'\n      );\n    }\n\n    function pushToSessionStorage(req) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      parsed.push(req);\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function replaceInSessionStorage(completedRequest) {\n      if (!supportsSessionStorage()) {\n        return;\n      }\n      var parsed = getParsedSessionStorage();\n      // Unlike requests held in the namespace, no session-stored requests can share object equality\n      // with the completed request, due to the string serialization. Instead, we must look for an\n      // item with the same \"__processed\" time. In case multiple requests are added simultaneously,\n      // the url and method are used to further disambiguate the serialized requests.\n      for (\n        var storedRqNumber = 0;\n        storedRqNumber < parsed.length;\n        ++storedRqNumber\n      ) {\n        var r = parsed[storedRqNumber];\n        if (\n          r.__processed === completedRequest.__processed &&\n          r.url === completedRequest.url &&\n          r.method === completedRequest.method\n        ) {\n          parsed[storedRqNumber] = completedRequest;\n          break;\n        }\n      }\n      window.sessionStorage.setItem(NAMESPACE, JSON.stringify(parsed));\n    }\n\n    function polyfillFormDataEntries() {\n      var originalAppend = FormData.prototype.append;\n      FormData.prototype.append = function () {\n        this.__entries = this.__entries || [];\n        this.__entries.push(Array.prototype.slice.call(arguments));\n        originalAppend.apply(this, arguments);\n      };\n      FormData.prototype.entries = function () {\n        return this.__entries;\n      };\n    }\n  }).apply(null, arguments)","args":[]},"result":{"value":{"requests":[]}},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"result"},{"name":"setupInterceptor","result":{"requests":[]},"sessionId":"d6ad5db7f3ef81a01bf2dae18de70aaa","cid":"0-0","type":"result"}],"retries":0,"state":"passed","events":[],"errorIndex":0,"end":"2022-04-25T06:07:50.359Z"}
[2022-04-25T09:07:50.360] [INFO] debug - onHookStart: 0-0:hook-10-5`

**Comment by rpii** [comment]
no,  thats what saves the json file of the report.  for each suite you
should see the console messages that are in that fragment

**Comment by rafalf** [comment]
Its happening for me all the time in v.8.0.0
Downgraded 
`"wdio-html-nice-reporter": "^7.7.14",`
and the issue is no longer showing 
7.9.1 looks ok too

**Comment by rpii** [comment]
OK I think I found what that was.  please try 8.0.1 and let me know.

Rich

**Comment by rafalf** [comment]
[2022-05-28T09:50:02.854] [INFO] default - Html Generation started
[2022-05-28T09:50:02.857] [INFO] default - Json write starting: /Users/rafalfusik/gitprojects/omp/reports/html-reports/Hiring%20Manager%20L2%20has%20active%2Finactive%20employeessuite1/0-1/report.json
[2022-05-28T09:50:03.930] [INFO] default - Json write completed: /Users/rafalfusik/gitprojects/omp/reports/html-reports/Hiring%20Manager%20L2%20has%20active%2Finactive%20employeessuite1/0-1/report.json
[2022-05-28T09:50:04.007] [INFO] default - Report Aggregation started
[2022-05-28T09:50:04.041] [INFO] default - Aggregated 2 specs, 2 suites, 2 reports, 
[2022-05-28T09:50:04.042] [INFO] default - Html Generation started
[2022-05-28T09:50:04.043] [INFO] default - Json write starting: /Users/rafalfusik/gitprojects/omp/reports/html-reports/master-report.json
[2022-05-28T09:50:04.045] [INFO] default - Report Aggregation completed
[2022-05-28T09:50:04.093] [INFO] default - copyfiles complete : /Users/rafalfusik/gitprojects/omp/node_modules/wdio-html-nice-reporter/css/ to /Users/rafalfusik/gitprojects/omp/reports/html-reports/


but the aggregate **report html** is not created for some reason 

i checked:
$ ls -la /Users/rafalfusik/gitprojects/omp/node_modules/wdio-html-nice-reporter/css/
total 64
drwxr-xr-x   4 rafalfusik  staff    128 28 May 09:48 .
drwxr-xr-x  15 rafalfusik  staff    480 28 May 09:48 ..
-rw-r--r--   1 rafalfusik  staff  23320 26 Oct  1985 glyphicons-halflings-regular.woff
-rw-r--r--   1 rafalfusik  staff   7631 26 Oct  1985 report-styles.css

Have a question for you, what's the setting to get screenshots w/o the video reporter 

![image](https://user-images.githubusercontent.com/445435/170816362-06785b0c-ef55-46ea-aba1-f42d27781f57.png)

I cant get it to work, screenshots are never taken 


```
        ["html-nice", {
            debug: true,
            outputDir: './reports/html-reports/',
            filename: 'report.html',
            reportTitle: 'HTML Report',
            linkScreenshots: true,
            //to show the report in a browser when done
            showInBrowser: false,
            collapseTests: false,
            //to turn on screenshots after every test
            useOnAfterCommandForScreenshot: true,
            LOG: logger
        }]
```

**Comment by rpii** [comment]
So are you saying that it is still failing?

On the video:so make sure that useOnAfterCommandForScreenshot is false in
the report aggregator constructor.
I am using just

        [video, {
            saveAllVideos: true,       // If true, also saves videos for
successful test cases
            videoSlowdownMultiplier: 3, // Higher to get slower videos,
lower for faster videos [Value 1-100]
            videoRenderTimeout: 5,      // Max seconds to wait for a video
to finish rendering\
            outputDir: 'reports/html-reports/screenshots',
        }],

and that works..

**Comment by rafalf** [comment]
video note:
it works for me with the video on my mac, but I am having issues installing modules required by video on Linux minimalistic (no GUI), hence would like to have screenshots without the video reporter

```
reporters: [
        'spec',
        // [video, {
        //     saveAllVideos: false,       // If true, also saves videos for successful test cases
        //     videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
        //     videoRenderTimeout: 5,      // Max seconds to wait for a video to finish rendering\
        //     outputDir: 'reports/html-reports/screenshots',
        // }],
        ["html-nice", {
            debug: true,
            outputDir: './reports/html-reports/',
            filename: 'report.html',
            reportTitle: 'HTML Report',
            linkScreenshots: true,
            //to show the report in a browser when done
            showInBrowser: false,
            collapseTests: false,
            //to turn on screenshots after every test
            useOnAfterCommandForScreenshot: true,
            LOG: logger
        }]
    ],
```

**Comment by rafalf** [comment]
> So are you saying that it is still failing?

yes, it doesnt produce the master hmtl file for me, even though logs says otherwise 
![Screenshot 2022-05-29 at 11 12 39](https://user-images.githubusercontent.com/445435/170860810-485ff885-f15e-43a4-a7ca-c82bc897f4f3.png)

**Comment by rpii** [comment]
Are you showing that in intelliJ?  it may not have refreshed that folder.

**Comment by rpii** [comment]
Can everyone try version 8.0.2.  I fixed another async issue. json files
should now be generated

Rich

**Comment by rafalf** [comment]
Hi Rich, 

Still not working 


Rafals-MacBook-Air:html-reports rafalfusik$ ls -la
total 0
drwxr-xr-x  5 rafalfusik  staff  160 May 30 21:21 .
drwxr-xr-x  4 rafalfusik  staff  128 May 27 14:54 ..
drwxr-xr-x  3 rafalfusik  staff   96 May 30 21:20 Hiring%20Manager%20L1%20has%20active%2Finactive%20employeessuite1
drwxr-xr-x  3 rafalfusik  staff   96 May 30 21:21 Hiring%20Manager%20L2%20has%20active%2Finactive%20employeessuite1
drwxr-xr-x  2 rafalfusik  staff   64 May 30 21:19 screenshots

this time around, no json, no master report to css generated 

```
[2022-05-30T21:21:13.603] [INFO] default - Json report write starting: /Users/rafalfusik/gitprojects/omp/reports/html-reports/Hiring%20Manager%20L2%20has%20active%2Finactive%20employeessuite1/0-1/report.json
[2022-05-30T21:21:17.582] [INFO] default - Json write completed: /Users/rafalfusik/gitprojects/omp/reports/html-reports/Hiring%20Manager%20L2%20has%20active%2Finactive%20employeessuite1/0-1/report.json
[2022-05-30T21:21:17.662] [INFO] default - Report Aggregation started
[2022-05-30T21:21:17.689] [INFO] default - Included metrics for suite: 0-0
[2022-05-30T21:21:17.690] [INFO] default - Included metrics for suite: 0-1
[2022-05-30T21:21:17.693] [INFO] default - Aggregated 2 specs, 2 suites, 2 reports, 
[2022-05-30T21:21:17.694] [INFO] default - Html Generation started
[2022-05-30T21:21:17.695] [INFO] default - Json report write starting: /Users/rafalfusik/gitprojects/omp/reports/html-reports/master-report.json
```

**Comment by rpii** [comment]
Thats ugly.  seems to have fixed the first problem and made the second one
worse.  Do you have this code in your project?

    onComplete: function (exitCode, config, capabilities, results) {
        (async () => {
            await reportAggregator.createReport();
        })();
    }

**Comment by rafalf** [comment]
I use the same code all the time, just changing the version...

**Comment by rpii** [comment]
Weird,  are you using mocha or cucumber.?  maybe try it again... Ive tested
on 5 or 6 machines and its working there

thanks
Rich

**Comment by rpii** [comment]
Ok.  I found a big test that fails.  Looking into it

**Comment by rafalf** [comment]
Jasmine, here is the full config 

```
const { ReportAggregator } = require("wdio-html-nice-reporter");
// const video                = require('wdio-video-reporter');
const log                  = require('log4js');
log.configure({
    appenders: {
        fileLog: {
            type: 'file',
            filename: "logs/html-reporter.log",
            maxLogSize: 5000000,
            level: 'debug'
        },
        debugLog: {
            type: 'file',
            filename: "logs/debug-html-reporter.log",
            maxLogSize: 5000000,
            level: 'debug'
        },
        'out': {
            type: 'stdout',
            layout: {
                type: "colored"
            }
        },
        'filterOut': {
            type: 'stdout',
            layout: {
                type: "colored"
            },
            level: 'info'
        }
    },
    categories: {
        file: {appenders: ['fileLog'], level: 'info'},
        default: {appenders: ['out', 'fileLog'], level: 'info'},
        console: {appenders: ['out'], level: 'info'},
        debug: {appenders: ['debugLog'], level: 'debug'}
    }
});

//pick the category above to match the output you want.
let logger = log.getLogger("default");

exports.config = {

    //
    // ====================
    // Runner Configuration
    // ====================
    //
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
    suites: {
        omp_dev: [
            './test/specs/aaa.spec.js',
        ],
        omp_employee: [
        ],
        omp_ats: [
        ]
    },
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 1,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 1,

        // chrome options and capabilities
        // https://webdriver.io/docs/options/#capabilities
        browserName: 'chrome',
        "goog:chromeOptions": {
            "excludeSwitches": [ "enable-automation" ],
            args: [
                '--window-size=1440,900',
                '--no-sandbox',
            ],
            prefs: {
                download: {
                    'prompt_for_download': false,
                    'directory_upgrade': true,
                    'default_directory': require('path').resolve(__dirname, 'download')
                },
                credentials_enable_service: false,
                profile: {
                    'password_manager_enabled': false
                }
            },
        },
        
        acceptInsecureCerts: true
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'debug',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['chromedriver'],
    
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'jasmine',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    specFileRetries: 1,

    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    // https://github.com/presidenten/wdio-video-reporter
    // https://github.com/rpii/wdio-html-reporter

    reporters: [
        'spec',
        // [video, {
        //     saveAllVideos: false,       // If true, also saves videos for successful test cases
        //     videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
        //     videoRenderTimeout: 5,      // Max seconds to wait for a video to finish rendering\
        //     outputDir: 'reports/html-reports/screenshots',
        // }],
        ["html-nice", {
            debug: true,
            outputDir: './reports/html-reports/',
            filename: 'report.html',
            reportTitle: 'HTML Report',
            linkScreenshots: true,
            //to show the report in a browser when done
            showInBrowser: false,
            collapseTests: false,
            //to turn on screenshots after every test
            useOnAfterCommandForScreenshot: true,
            LOG: logger
        }]
    ],
    
    //
    // Options to be passed to Jasmine.
    jasmineOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: 60000,
        //
        // The Jasmine framework allows interception of each assertion in order to log the state of the application
        // or website depending on the result. For example, it is pretty handy to take a screenshot every time
        // an assertion fails.
        expectationResultHandler: function(passed, assertion) {
            // do something
        }
    },
    
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {Number} exitCode 0 - success, 1 - fail
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {Number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * @param {Object}  test             test object
     * @param {Object}  context          scope object the test was executed with
     * @param {Error}   result.error     error object in case the test fails, otherwise `undefined`
     * @param {Any}     result.result    return object of test function
     * @param {Number}  result.duration  duration of test
     * @param {Boolean} result.passed    true if test has passed, otherwise false
     * @param {Object}  result.retries   informations to spec related retries, e.g. `{ attempts: 0, limit: 0 }`
     */
    // afterTest: function(test, context, { error, result, duration, passed, retries }) {
    // },


    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }

    onPrepare: function (config, capabilities) {

        let reportAggregator = new ReportAggregator({
            outputDir: './reports/html-reports/',
            filename: 'master-report.html',
            reportTitle: 'Master Report',
            browserName : 'chrome',
            LOG: logger,
            collapseTests: true
        });
        reportAggregator.clean() ;
        global.reportAggregator = reportAggregator;
    },

    onComplete: function(exitCode, config, capabilities, results) {
        (async () => {
            await global.reportAggregator.createReport();
        })();
    },

}

```

**Comment by rpii** [comment]
Can everyone try version 8.0.2.  I fixed another async issue. json files
should now be generated

Rich

**Comment by rafalf** [comment]
@rpii I tested before with 8.0.2
but this time around tested with 
        "wdio-html-nice-reporter": "^8.0.5",
and still not working, config etc as above in my comments

**Comment by alpako** [comment]
Hi,
after updating to wdio-html-nice-reporter 8.1.0 I ran into this problem. Sometimes the _master-report.html_ file was not created, sometimes the _report-styles.css_ file. The code in _onComplete_ never waits for the completion of _createReport()_, since it is not possible to use _await_ in a synchronous function.
```js
onComplete: function (exitCode, config, capabilities, results) {
    (async () => {
        await reportAggregator.createReport();
    })();
}
```

Using the following _onComplete_ function report generation seem to be working again.
```js
async onComplete: function (exitCode, config, capabilities, results) {
    await reportAggregator.createReport();
}
```

Could someone please confirm whether change resolves their issues with report generation?

**Comment by AlexRRR** [comment]
@alpako  it works for me! I was going CRAZY because of this issue. Thanks for sharing.
